package com.gopay.transcript;

import com.fasterxml.jackson.annotation.JsonValue;

public enum TranscriptType {
    //Core Api Adapter
    CAA_CHARGE("CAA_CHARGE"),
    CAA_CAPTURE("CAA_CAPTURE"),
    CAA_CANCEL("CAA_CANCEL"),
    CAA_REFUND("CAA_REFUND"),
    CAA_SETTLE("CAA_SETTLE"),
    CAA_EXPIRY("CAA_EXPIRY"),
    CAA_INQUIRY("CAA_INQUIRY"),
    CAA_PAYMENT("CAA_PAYMENT"),

    //Merchant Gopay User Payment Api
    MGUPA_PAYMENT("MGUPA_PAYMENT"),

    //Guest Payment
    GPA_PAYMENT("GPA_PAYMENT"),
    GPA_CAPTURE("GPA_CAPTURE"),
    GPA_CANCEL("GPA_CANCEL"),
    GPA_REFUND("GPA_REFUND"),
    GPA_SETTLE("GPA_SETTLE"),
    GPA_EXPIRY("GPA_EXPIRY"),

    //Bank Api
    BANK_INQUIRY("BANK_INQUIRY"),
    BANK_PAYMENT("BANK_PAYMENT"),

    //Order Management Service
    OMS_CREATE("OMS_CREATE"),
    OMS_CREATE_AND_PROCESS("OMS_CREATE_AND_PROCESS"),
    OMS_PROCESS("OMS_PROCESS"),
    OMS_CANCEL("OMS_CANCEL"),

    //Boomerang Service
    BOOMERANG_REFUND("BOOMERANG_REFUND"),

    //Recurring Payment Service
    RPS_CREATE("RPS_CREATE"),
    RPS_CANCEL("RPS_CANCEL"),
    RPS_ADD_ORDER("RPS_ADD_ORDER"),

    //Authorization Service
    AS_MERCHANT_INTROSPECT("AS_MERCHANT_TOKEN_INTROSPECT"),
    AS_FRAUD_CHALLENGE("AS_FRAUD_CHALLENGE"),
    AS_GENERATE_TOKEN("AS_GENERATE_TOKEN"),

    //Payment Option Service
    POS_GET_PAYMENT_OPTIONS("POS_GET_PAYMENT_OPTIONS"),

    // Bonsai Service
    BONSAI_GET_SHORT_LINK("BONSAI_GET_SHORT_LINK"),

    //Checkout Service
    CS_FETCH_CUSTOM_ORDER_DETAILS("CS_FETCH_CUSTOM_ORDER_DETAILS"),

    //Dermawan Service
    DERMAWAN_FETCH_PROMOTION("DERMAWAN_FETCH_PROMOTION"),

    //User Service
    US_FETCH_PROFILE("US_FETCH_PROFILE"),

    //Notification Service
    NC_SEND_SMS_NOTIF("NC_SEND_SMS_NOTIF"),
    NC_SEND_PUSH_NOTIF("NC_SEND_PUSH_NOTIF"),

    //1OMS Clearing And Settlement Worker
    CNS_AUTHORIZE_EVENT("CNS_AUTHORIZE_EVENT"),
    CNS_CAPTURE_EVENT("CNS_CAPTURE_EVENT"),
    CNS_SETTLEMENT_EVENT("CNS_SETTLEMENT_EVENT"),
    CNS_DENY_EVENT("CNS_DENY_EVENT"),
    CNS_PENDING_EVENT("CNS_PENDING_EVENT"),
    CNS_CANCEL_EVENT("CNS_CANCEL_EVENT"),
    CNS_REFUND_EVENT("CNS_REFUND_EVENT"),
    CNS_ONLINE_REFUND_EVENT("CNS_ONLINE_REFUND_EVENT"),
    CNS_REFUND_TO_BANK_EVENT("CNS_REFUND_TO_BANK_EVENT"),
    CNS_PARTIAL_REFUND_EVENT("CNS_PARTIAL_REFUND_EVENT"),
    CNS_CHARGEBACK_EVENT("CNS_CHARGEBACK_EVENT"),
    CNS_PARTIAL_CHARGEBACK_EVENT("CNS_PARTIAL_CHARGEBACK_EVENT"),
    CNS_EXPIRE_EVENT("CNS_EXPIRE_EVENT"),
    CNS_FAILURE_EVENT("CNS_FAILURE_EVENT"),
    CNS_PARTIAL_SETTLEMENT_EVENT("CNS_PARTIAL_SETTLEMENT_EVENT"),
    CNS_REVERSAL_EVENT("CNS_REVERSAL_EVENT");

    private final String type;

    TranscriptType(String type) {
        this.type = type;
    }

    @JsonValue
    public String jsonValue() {
        return this.type;
    }
}
